-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.2.3
    hooks:
      -   id: check-added-large-files
      -   id: check-case-conflict
      -   id: check-executables-have-shebangs
      -   id: check-json
      -   id: check-merge-conflict
      -   id: check-symlinks
      -   id: check-yaml
      -   id: check-xml
      -   id: detect-private-key
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
