package org.datavaultplatform.common.model;

public enum Permission {

    VAULT_PERMISSION_1,
    VAULT_PERMISSION_2,
    VAULT_PERMISSION_3,
    VAULT_PERMISSION_4,
    VAULT_PERMISSION_5,

    SCHOOL_PERMISSION_1,
    SCHOOL_PERMISSION_2,
    SCHOOL_PERMISSION_3,
    SCHOOL_PERMISSION_4,
    SCHOOL_PERMISSION_5,

    ADMIN_PERMISSION_1,
    ADMIN_PERMISSION_2,
    ADMIN_PERMISSION_3,
    ADMIN_PERMISSION_4,
    ADMIN_PERMISSION_5
}
