# Created by David Hay 31Oct2022 / Updated 29Apr2026
# Used to create custom docker image for Jenkins docker builds
#
# used 'eclipse-temurin:21.0.10_7-jdk' as base java21 image because it has addgroup/adduser/gpasswd
#
# added User[jenkins] and Groups[jenkins,docker]
# added User[jenkins] to Group[docker]
# all the User/Group stuff is to ensure that -
# the jenkins user within this container can access /var/run/docker.sock
#
# added tools jq, curl and ping to help with testing and diagnostics
#
# THIS SPECIFIC VERSION OF eclipse-temurin:21 works - dated 2026-04-29 (had problems with some other versions)
#https://hub.docker.com/layers/library/eclipse-temurin/21.0.10_7-jdk/images/sha256-53e0a987e4ee9832c7e668929fc2c0cfdbb874b3ed2b1ed2ed333b688cc6bc1d
FROM eclipse-temurin@sha256:e58e492628c1428ceb838afc1a1b8762673d5eaa09296f560c363daea0fdcf3b
ARG JENKINS_UID
ARG JENKINS_GID
ARG DOCKER_GID
USER root
#
# install tools
#
RUN apt update
RUN apt upgrade -y
RUN apt install -y jq
RUN apt install -y curl
RUN apt install -y git
RUN apt install -y iputils-ping
#
# tweak users and groups to ensure 'jenkins' user can access docker socket (/var/run/docker.sock)
#
RUN addgroup docker --gid $DOCKER_GID
RUN addgroup jenkins --gid $JENKINS_GID
RUN adduser --disabled-password --gecos "Jenkins User" -u $JENKINS_UID --gid $JENKINS_GID jenkins
RUN gpasswd --add jenkins docker
USER jenkins
