# Created by David Hay 31Oct2022 / Updated 05Jul2026
# Used to create custom docker image for Jenkins docker builds
#
# used 'eclipse-temurin:26.0.1_8-jdk' as base java26 image because it has addgroup/adduser/gpasswd
#
# added User[jenkins] and Groups[jenkins,docker]
# added User[jenkins] to Group[docker]
# all the User/Group stuff is to ensure that -
# the jenkins user within this container can access /var/run/docker.sock
#
# added tools jq, curl and ping to help with testing and diagnostics
#
# THIS SPECIFIC VERSION OF eclipse-temurin:26 works - dated 2026-07-02 (had problems with some other versions)
#https://hub.docker.com/layers/library/eclipse-temurin/26.0.1_8-jdk/images/sha256-41ea5422a65bdcabc71758d9f1096c51a0cde34e006d7af085b81a3c0a8b7737
FROM eclipse-temurin@sha256:75f082a5188c432fcca40ee062b221646a551ca4c6542a6429750003f2f2409f
ARG JENKINS_UID
ARG JENKINS_GID
ARG DOCKER_GID
USER root
#
# install tools
#
RUN apt update
RUN apt upgrade -y
RUN apt install -y jq
RUN apt install -y curl
RUN apt install -y git
RUN apt install -y iputils-ping
#
# tweak users and groups to ensure 'jenkins' user can access docker socket (/var/run/docker.sock)
#
RUN addgroup docker --gid $DOCKER_GID
RUN addgroup jenkins --gid $JENKINS_GID
RUN adduser --disabled-password --gecos "Jenkins User" -u $JENKINS_UID --gid $JENKINS_GID jenkins
RUN gpasswd --add jenkins docker
USER jenkins
